= 管理项目
:proglang: Motoko
:IC: Internet Computer blockchain
:company-id: DFINITY

您可以通过修改每个项目的`+dfx.json+`配置文件来修改项目的一些关键设置。 您可以使用`+dfx config+`命令以程序化方式更改这些设置，也可以直接手动编辑`+dfx.json+`文件。

== 如何更改源文件目录

在使用`+dfx build+`命令编译项目的源代码之前，您可能需要检查用于存储程序源代码的默认位置。默认情况下，用于创建新项目的名称是用于一个数据Canister (`+canister_name+`)和一个资源canister (`+canister_name_assets+`)的名称，并且程序源代码应位于src/canister_name目录中。

但是，根据应用程序的复杂度和体系结构，您可能需要修改源代码的默认位置。

例如，对于一个简单的程序，您可能想要去掉一个目录层级，并将源代码放在+src+目录中：

[source,text]
----
  "main": "src/main.mo",
----

对于更复杂的应用程序，您可能需要使用多层目录结构：

[source,text]
----
"canisters": {
  "profiles": {
    "main": "src/profiles/utils/main.mo"
  },
  "events": {
    "main": "src/events/calendar/main.mo"
  },
  "media": {
    "main": "src/events/reports/main.mo"
  }
}
----

提示：如果您修改源代码目录的默认设置，请确保dfx.json配置文件中的设置与文件系统上的目录位置匹配。

////
== How to change your output directory

When you compile source code for your project using the `+dfx build+` command, the command automatically generates a WebAssembly executable and interface bindings in a default output folder. 
You can customize the default output folder for a project by modifying the project’s local `+dfx.json+` configuration file. 
You can change settings in the `+dfx.json+` configuration file manually by editing the file or programmatically by running the `+dfx config+` command.

To see the default output folder you are currently using, run the following command:

[source,bash]
----
dfx config defaults.build.output
----

The command returns the setting you have currently defined in the `+dfx.json+` configuration file. 
For example:

[source,bash]
----
"canisters/"
----

To change the default output folder, run the `+dfx config+` command and specify a new location. 
For example, to change the default output directory from `+canisters+` to `+ready_for_release+`, run the following command:

[source,bash]
----
dfx config defaults.build.output ready_for_release
----

This command changes the `+output+` setting in the `+dfx.json+` configuration file to `+ready_for_release+`.

For example:

[source,json]
----
  "defaults": {
    "build": {
      "output": "ready_for_release"
----
////

== 如何修改主程序文件名

在使用 `+dfx build+` 命令编译项目的源代码之前，应验证用于程序源代码的位置和文件名。

例如，如果要为 `+factorial+` 程序构建容器，并且该程序的源代码位于 `+src/math/factorial.mo+` 中，您应确保在配置文件的Canister部分指定了正确的路径。

例如：

[source,json]
----
"main": "src/math/factorial.mo",
----

请记住，更改程序文件名的配置设置仅会影响dfx build命令在哪里寻找要编译的源代码。在配置文件中进行更改不会重命名文件系统上的任何文件或目录。如果更改主程序文件的路径或文件名，请确保更改项目目录中的名称和位置。

== 如何更改应用前端服务的位置

您可以通过修改dfx.json配置文件中的设置来更改默认的主机名和端口号，以运行本地Internet Computer副本进程并为应用程序前端提供服务。

例如：

[source,json]
----
"networks": {
  "local": {
    "bind": "192.168.47.1:8000",
    "type": "ephemeral"
  }
}
----
