= 设计应用
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY

在您提出应用程序构想时，您将做出许多有关如何构建和组织项目的设计决定。这些设计决定中的大多数与您将应用程序部署在传统云服务还是Internet Computer上无关。但是，如果要在Internet Computer上进行部署，则在规划应用程序的实现时，应特别注意一些设计决策。

CAUTION: 此部分正在进行中且不完整。 随着构建在 {IC} 上运行的 dapp 的最佳实践和设计模式不断发展，此处包含的信息也将相应地发展和变化。

== 单或多个Canister架构

在设计应用程序时，您首先要考虑的是将其封装在单个容器中还是由多个容器组成。

例如，如果要编写没有前端的简单服务，您可能想要使用单个容器来简化项目管理和维护，并着重于添加功能。如果您的应用程序同时具有前端资源和后端业务逻辑，则您的项目可能至少包含两个容器，一个容器用于管理用户界面组件，另一个容器用于应用程序提供的后端服务。

在规划中，您可能还考虑将一些常见的可重用服务放在其自己的容器中，以便可以从其他更专业的容器中导入和调用它们，或将其提供给其他开发人员使用。LinkedUp示例应用程序通过将专业服务应用分为两个容器来说明此方法。

在link:https://github.com/dfinity/linkedup[LinkedUp]示例中，建立社交连接的功能在connectd Canister中定义，并且与用于设置在linkedup Canister中定义的专业配置的功能分开。

很容易想象用第三个Canister来扩展应用，例如基于配置属性和共享连接来安排事件。

== 将Actor从类型和实用程序区分开

在规划项目的体系结构时，一种常见的做法是将主要Actor的代码放在一个文件中，并使用单独的其他文件来定义程序使用的类型和不需要Actor的实用程序功能。‌
例如，您可以将应用程序的后端逻辑设置为包含以下文件：‌

* `+Main.mo+`或`+main.rs+`具有Actor发送查询和更新调用的功能。
* 具有助手功能的`+Util.mo+`或`+Util.mo+`可以导入以供actor使用。
* `+Types.mo+`或`+types.rs+`，其中包含应用程序的所有数据类型定义。

== 使用查询调用

如link:../developers-guide/concepts/canisters-code{outfilesuffix}#query-update[查询和更新方法]中所述，查询返回结果比更新调用更快。 因此，将功能明确标记为查询是提高应用程序性能的有效策略。 在规划和设计阶段，应考虑如何更好地使用查询调用，而不是可以执行查询或更新的功能。

这是遵循的良好通用规则，可以广泛应用于大多数类别的应用程序。 但是，您还应该考虑安全性和性能之间的折衷，即查询无法达成共识。 对于某些应用程序，这种折衷可能是合适的。 例如，如果您正在开发博客平台，则检索与标签匹配的文章的查询可能不必保证通过共识来确保大多数节点都同意结果。 但是，如果您的应用程序正在检索敏感信息（例如财务数据），则可能需要提供更多有关结果的保证。

作为基本查询的替代方法，Internet Computer还支持经过认证的查询。 认证查询使您能够接收信任的认证响应。 使用认证查询是一种高级技术，在教程或其他以开发人员为中心的文档中均未涉及，但是您可以了解身份验证的工作原理，以及如何配置程序以响应接口规范中的查询返回认证数据。

== 数据存储与检索

对于许多应用程序，数据库主要用于提供记录的长期存储，可以使用一个或多个关键字段有效地检索记录。在Internet Computer上，通常通过诸如哈希表之类的数据结构来解决这种用例。代替传统的数据库，Internet Computer使您可以使用稳定的内存来处理长期数据存储（通常称为正交持久性），并可以使用查询调用来检索数据。 尽管这种方法适用于大多数应用程序和简单的键值数据库请求，但它不能完全模拟关系数据库。