= 安装、升级、删除软件
:experimental:
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY

如link:../quickstart/quickstart-intro{outfilesuffix}[快速入门]中所述，您可以通过在终端中运行命令来下载并安装最新版本的 DFINITY Canister SDK 软件包。 本节中的主题提供有关安装，升级和删除 DFINITY Canister SDK 的其他信息。

include::ROOT:page$download.adoc[leveloffset=0,tag=install]

== What gets installed

DFINITY Canister SDK安装脚本会在本地计算机上的默认位置安装多个组件。 下表描述了安装脚本将安装的开发环境组件：

[cols="20,55,25",options="header"]
|===
|组件
|描述
|默认位置

|dfx
|DFINITY 可执行命令行接口 (CLI)
|`+/usr/local/bin/dfx+`

|moc
|Motoko运行时编译器
|~/.cache/dfinity/versions/<VERSION>/moc

|replica
|Internet Computer 本地网络二进制文件
|`~/.cache/dfinity/versions/<VERSION>/replica`

|uninstall.sh
|删除 DFINITY Canister SDK 及其所有组件的脚本
|`~/.cache/dfinity`

|versions
|包含安装的每个DFINITY Canister SDK版本的缓存子目录
|`~/.cache/dfinity/versions`

|===

=== Core components in a versioned directory

`~/.cache/dfinity/versions` 目录存储DFINITY Canister SDK的一个或多个版本子目录。 每个版本的子目录包含特定版本的DFINITY Canister SDK所需的所有目录和文件。

例如，如果列出 `~/.cache/dfinity/versions/0.8.2` 目录的内容，则会看到以下核心组件。

....
total 349192
drwxr-xr-x  17 pubs  staff       544 Mar 15 11:55 .
drwxr-xr-x   4 pubs  staff       128 Mar 25 14:36 ..
drwxr-xr-x  49 pubs  staff      1568 Mar 15 11:55 base
drwxr-xr-x  20 pubs  staff       640 Mar 15 11:55 bootstrap
-r-x------   1 pubs  staff  66253292 Mar 15 11:55 dfx
-r-x------   1 pubs  staff  10496256 Dec 31  1969 ic-ref
-r-x------   1 pubs  staff   5663644 Dec 31  1969 ic-starter
-r-x------   1 pubs  staff      9604 Dec 31  1969 libcharset.1.0.0.dylib
-r-x------   1 pubs  staff     38220 Dec 31  1969 libffi.7.dylib
-r-x------   1 pubs  staff    668300 Dec 31  1969 libgmp.10.dylib
-r-x------   1 pubs  staff    958248 Dec 31  1969 libiconv.2.4.0.dylib
-r-x------   1 pubs  staff      4200 Dec 31  1969 libiconv.dylib
-r-x------   1 pubs  staff     96900 Dec 31  1969 libz.1.2.11.dylib
-r-x------   1 pubs  staff  15417684 Dec 31  1969 mo-doc
-r-x------   1 pubs  staff  14634020 Dec 31  1969 mo-ide
-r-x------   1 pubs  staff  15111508 Dec 31  1969 moc
-r-x------   1 pubs  staff  49404128 Dec 31  1969 replica
....

=== Motoko base 库目录

DFINITY Canister SDK的版本子目录中的主目录包含与该版本的DFINITY Canister SDK兼容的Motoko基础库模块。 由于Motoko基础库的发展迅速，因此，您应仅使用与已安装的DFINITY Canister SDK版本打包在一起的基础模块。

=== Bootstrap 目录

Bootstrap目录包含已弃用的Web服务器代码。 从版本0.7.0开始，代理可以调用HTTP中间件服务器代替引导程序代码。 这个更改可使Canister可以直接响应HTTP请求，并且可以像传统基于Web的应用程序一样操作。

== 升级到最新版

如果初始安装后有新版本可下载，您应当尽早安装新版本以得到最新的修补和增强。您可以使用`+dfx upgrade+`命令将当前安装的版本与可下载的最新版本进行比较。如果有较新版本的dfx，则`+dfx upgrade+`命令将自动下载并安装最新版本。

在安装新版本之前，您无需卸载软件。但是，如果要执行全新安装而不是升级，则可以按照xref:remove[卸载软件]中的说明先卸载软件，然后重新运行download and installation命令。

有关最新版本中的特点和修补的信息，请参阅xref:release-notes:sdk-release-notes.adoc[发行说明]。

[[remove]]
== 卸载软件

当您安装 {sdk-short-name} 时，安装脚本会将所需的二进制文件放在本地目录中并创建缓存。 您可以通过运行.cache文件夹中的 `+uninstall+` 脚本从本地计算机中删除SDK二进制文件和缓存。

For example:
[source,bash]
----
~/.cache/dfinity/uninstall.sh
----

如果您是想卸载软件后立即重新安装一个干净版本，运行以下命令：

[source,bash]
----
~/.cache/dfinity/uninstall.sh && sh -ci "$(curl -sSL https://sdk.dfinity.org/install.sh)"
----
