= 使用不用的语言开发
:cpp: C++

本文档中的大多数示例都使用Motoko（一种专门设计用于Internet Computer的编程语言）。但是，您可以使用可编译为WebAssembly的任何语言编写程序，以部署在Internet Computer上运行的应用程序。

== Rust

您可以使用Cargo编译程序并使用WebAssembly作为输出来创建一个Rust项目运行在Internet Computer上。

本节总结了在Internet Computer上将Rust程序作为Canister部署时所涉及的关键步骤。然而，您应该知道，此处描述的步骤仅说明了一种方法，其他的实现方式也是可能的。

请注意，link:https://github.com/dfinity/cdk-rs[Rust Canister开发工具包（Rust CDK）] 提供了一些快捷方式，可简化编写查询和更新函数调用的过程，并提供了一些link:https://github.com/dfinity/cdk-rs/tree/next/examples[示例]来帮助您开始构建基于Rust的项目，但您也可以为Internet Computer开发应用程序而不使用Rust CDK。

=== 创建项目

因为大部分的Rust程序员使用Cargo来处理创建和包管理任务（储如下载和编译依赖库），首先使用Cargo命令行接口来创建一个新的Rust项目。

或者，您可以使用DFINITY Canister软件开发包(SDK)来代替Cargo创建新的项目，但是使用Cargo来创建新项目代表了Rust项目的典型工作流程。

创建一个新项目：

[arabic]
. 在本地计算机上打开终端。
. 运行以下命令以验证Cargo是否安装：
+
[source,bash]
----
cargo --version
----
. 更改您的IC或Rust示例项目的目录。
. 运行类似以下命令来创新项目：
+
[source,bash]
----
cargo new my_rust_dapp
----
+
该命令创建一个新的`+my_rust_dapp+`目录，包含了默认的`+Cargo.toml+`文件和带有默认`+main.rs+`文件的`+src+`目录。
. 运行以下命令进入到项目录：
+
[source,bash]
----
cd my_rust_dapp
----
+
如果您显示该目录内容，您将看到目录下仅包含`+Cargo.toml+`文件和`+src+`目录。为了编译项目以使能在Internet Computer上运行，您还需要一些其他文件。

=== 修改Cargo配置文件

*manifest* 文件为每个Rust包提供一个清单。清单包含了包的配置明细。为准备Rust项目运行在Internet Computer上，我们需要拷贝默认的*manifest*文件并修改一些详细配置信息。

修改`+Cargo.toml+`文件：

. 如果有必要，运行pwd命令来检查您是否在项目的根目录下。
. 运行以下命令拷贝默认的`+Cargo.toml+`文件到src目录：
+
[source,toml]
----
cp Cargo.toml src/Cargo.toml
----
+
在Internet Computer上运行的项目通常使用一个项目级别的`+Cargo.toml+`文件为项目的Canister成员设置工作区，并在源代码目录中使用第二个`+Cargo.toml+`文件为每个Canister配置参数。
. 用文本编辑器打开项目根目录下的`+Cargo.toml+`文件
+
默认情况下，该文件包含[package]和[dependencies]部分。
. 用类似以下`+[workspace]+`部分来替换`+[package]+`：
+
[source,toml]
----
[workspace]
members = [
    "src/my_rust_dapp",
]
----
+
有关`+[workspace]+`部分和键值信息，请参阅link:https://doc.rust-lang.org/cargo/reference/workspaces.html[Workspaces]。有关`+Cargo.toml+`配置的其他部分和键值，请参阅link:https://doc.rust-lang.org/cargo/reference/manifest.html[清单格式]。
. 删除`+[dependencies]+`
. 部分保存并关闭文件
. 在文本编辑器中打开`+src/Cargo.toml+` 文件
. 增加类似以下带有主要源代码目录的`+[lib]+`
+
[source,toml]
----
[lib]
path = "main.rs"
----
. 更新`+[dependencies]+`部分的依赖项
. 保存并关闭文件。

=== Add a canister configuration file

当您用{sdk-short-name}创建一个新项目时，`+dfx new+`命令自动添加一个默认`+dfx.json+`配置文件到项目目录。因为他们已经使用Cargo来创建Rust项目，所以您需要手工在项目目录下创建该文件。

添加`+dfx.json+`配置文件：

. 如有必要，用pwd命令来检查您是否仍在项目目录下。
. 在项目根目录下创建一个dfx.json配置文件。
. 在文本编辑器中打开dfx.json文件。
. 添加类似以下设置的version和canisters键到dfx.json文件

+
[source,json]
----
{
  "version": 1,
  "canisters": {
    "my_rust_dapp": {
      "type": "custom",
      "candid": "src/my_rust_dapp.did",
      "wasm": "target/wasm32-unknown-unknown/debug/my_rust_dapp.wasm",
      "build": "cargo build --target wasm32-unknown-unknown --package my_rust_dapp"
    }
  }
}
----
+
让我们详细看看这些配置
+
--
* `+version+`用于标识创建项目软件的版本号
* `+version+`部分指定项目的Canister名字。在本例中，仅有一个名为my_rust_program的Canister
* 因为不是可标识的canister类型之一（motoko或assets），`+type+`键设置为custom
* `+candid+`键指定用于此项目的Candid接口描述文件的名称和位置。
* `+wasm+`键指定cargo编译命令生成的WebAssembly文件路径
* `+build+`键指定用于编译输出的cargo命令
--
+
这些是最小配置需要。随着您构建更复杂的程序，您会需要在 Cargo.toml, dfx.json中进行其他详细配置
. 保存并关闭文件。

=== 创建一个Candid接口描述文件

除了`+dfx.json+`配置文件之外，您还需要一个Candid接口描述文件（例如，`+my_rust_dapp.did+`），以映射程序输入参数和返回值格式到Candid中伪代码表现形式。

添加Candid接口描述文件：

. 如有必要，用`+pwd+`命令来检查您是否仍在项目目录下。
. 在项目的src目录下创建一个新的Candid接口描述文件（例如`+my_rust_dapp.did+`）
. 在文本编辑器中打开这个描述文件并且为程序中每一个函数添加描述。
+
例如，如果 `+my_rust_dapp+` 是一个简单的计数器程序，使用`+increment+`, `+read+`和`+write+`函数，`+my_rust_dapp.did+`看起来是这样的：
+
[source,candid]
----
service : {
  "increment": () -> ();
  "read": () -> (nat) query;
  "write": (nat) -> ();
}
----
. 保存并关闭文件。

=== 修改默认程序

当您创建一个新的项目，`+src+`目录包含了一个"Hello World!"的模板`+main.rs+`文件

修改模板源代码：

. 在文本编辑器中打开`+src/main.rs+`文件并删除存在的内容。
. 编写您想在 {IC} 上发布的程序。
+
编写程序时，请注意有两种类型的调用（更新调用和查询调用），更新函数使用异步消息
. 保存并关闭 src/main.rs文件。

=== 连接到网络并部署

在您部署和测试程序之前，您有以下工作要做：

* 连接您开发环境Internet Computer网络本地运行或连接到您能访问的子网上远程运行。
* 为您的应用注册一个网络特定标识符。
* 编译带有WebAssembly输出目标的程序。

因为您使用编译成WebAssembly的 `+cargo build+` 命令配置了自定义 `+dfx.json+` 文件，所以可以使用dfx命令行接口和标准工作流程来执行所有其余步骤。

本地生成和部署：

. 如有必要，用pwd命令来检查您是否仍在项目目录下。
. 打开一个新的终端窗口或tab页并进入项目目录。
+
例如，在macOS终端上执行以下任一操作：
--
* 单击Shell，在当前工作目录选择新选项卡以打开新的终端。
* 点击Shell，选择新窗口，在新终端运行cd ~/ic-projects/location_hello（如果location_hello项目在ic-projects工作目录）。
--
+
您现在应该打开了两个已进入当前工作目录的终端。
. 执行以下命令在本地计算机上启动Internet Computer网络。
+
[source,bash]
----
dfx start
----
+
根据您的平台和本地安全设置，您可能会看到一个警告。如果提示您允许或拒绝传入网络连接，请单点允许。
. 离开网络操作显示信息的终端并切换到原来的终端
. 运行以下命令为应用注册一个唯一Canister标识符：
+
[source,bash]
----
dfx canister create --all
----
. 运行以下命令构建程序：
+
[source,bash]
----
dfx build
----
. 运行以下命令在本地部署程序：
+
[source,bash]
----
dfx canister install --all
----
. 从命令行或浏览器测试功能。

== Using C

因为Internet Computer支持应用编译到标准的WebAssembly模块，您能用C, C++, Objective-C和Objective-C++语言标准编译器和工具和Clang编译器来生成应用程序。

为了说明如何迁移用C编写的程序以在Internet Computer上运行，让我们看一下 link:https://github.com/dfinity/examples/tree/master/c[示例库]中的简单reverse.c程序。reverse.c程序包含一个名为go的函数，该函数可以反转字符串。

=== 搭建开发环境

要将`+reverse.c+`程序编译为WebAssembly，需要安装clang编译器和标准库。 您可以通过运行以下命令来检查本地计算机上是否已安装clang：

[source,bash]
----
clang --version
----

如果安装了`+clang+`，该命令将显示类似于以下内容的信息：

....
clang version 10.0.0 
Target: x86_64-apple-darwin19.5.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
....

如果该命令未返回版本信息，请在继续之前安装clang。 根据您所使用的操作系统，安装clang的步骤会有所不同。 例如，在Debian Linux上，运行以下命令：

[source,bash]
----
sudo apt-get install clang lld gcc-multilib
----

在macOS上，您可以通过安装开发人员命令行工具或使用Homebrew安装LLVM来安装clang。 例如，如果未安装clang，请运行以下命令：

[source,bash]
----
brew install llvm
----

=== 将程序编译为WebAssembly

您可以先使用clang进行编译，然后使用wasm-ld进行链接，以将C程序编译为作为WebAssembly模块运行。 根据所使用的操作系统和Clang版本，您可能会使用其他版本的WebAssembly链接器，例如macOS上的wasm-ld或Debian上的wasm-ld-8。‌

在macOS上编译为WebAssembly：‌
 
. 通过运行以下clang命令来编译程序：‌
+
[source,bash]
----
clang --target=wasm32 -c -O3 reverse.c
----
. 通过运行以下wasm-ld命令，运行链接器以创建WebAssembly模块：‌
+
[source,bash]
----
wasm-ld --no-entry --export-dynamic --allow-undefined reverse.o -o reverse.wasm
----

=== 创建一个最小的配置文件

接下来，您需要准备一个简单的配置文件，标识了能安装在Internet Computer上的reverse二进制包和一个build目录，以便您能使用dfx命令行接口来作为Canister安装并运行。‌

准备配置文件和构建目录：‌

. 使用以下命令来创建一个带有canisters键的dfx.json文件
+
[source,bash]
----
echo '{"canisters":{"reverse":{"main":"reverse"}}}' > dfx.json
----
. 使用以下命令创建一个build目录‌
+
[source,bash]
----
mkdir build
----
. 运行以下命令创建一个reverse目录‌
+
[source,bash]
----
mkdir build/reverse
----
. 运行以下命令拷贝WebAssembly模块到新的build/reverse目录‌
+
[source,bash]
----
cp reverse.wasm build/reverse/
----

=== 创建一个最小接口描述文件

在标准开发工作流程中，运行dfx build命令会在Canister的输出目录中创建多个文件，包括一个或多个Candid接口描述（.did）文件，这些文件处理与程序功能关联的数据类型的类型匹配。‌

有关用于不同数据类型的语法的详细信息，请参见link:../candid-guide/candid-intro{outfilesuffix}[_Candid规范_] 和 link:https://github.com/dfinity/candid/tree/master/spec[Candid 指导]。

为此程序创建一个Candid接口描述文件：‌

. 在您为reverse.c程序源创建的build目录中打开一个终端。‌
. 创建一个名为reverse.did的新文本文件。‌
. 添加go函数的描述。‌
+
例如：
+
[source.bash]
----
service : {
  "go": (text) -> (text);
}
----
. 保存并关闭文件。

=== 部署和测试程序

在部署和测试程序之前，您需要执行以下操作：‌

* 连接到Internet Computer网络，该网络可以在您的开发环境中本地运行，也可以在您可以访问的子网中远程运行。
* 为应用注册一个特定网络标识。

在本地部署和测试：‌

. 在本地计算机上打开一个新的终端窗口或选项卡。‌
+
例如，如果在macOS上运行Terminal，请单击Shell，然后选择New Tab在当前工作目录中打开一个新终端。‌
. 通过运行以下命令，在第二个终端中的本地计算机上启动Internet Computer网络：‌
+
[source,bash]
----
dfx start
----
. 通过运行以下命令，为reverse应用程序注册唯一的容器标识符‌
+
[source,bash]
----
dfx canister create --all
----
. 通过运行以下命令在本地网络上部署默认程序：‌
+
[source,bash]
----
dfx canister install --all
----
. 通过运行以下命令在程序中调用go函数：
+
[source,bash]
----
dfx canister call reverse go reward
("drawer")
----

您可以在link:https://github.com/dfinity/examples/tree/master/c[示例库]中找到C程序的其他示例。
