= 管理 canister 智能合约
March 2020 (Alpha)
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY

如果您已经按照链接中的教程尝试使用 {sdk-long-name}：link:tutorials-intro{outfilesuffix}[教程] 部分或通过从链接中下载示例：link:https://github.com/dfinity/examples[示例]代码库，您已经熟悉如何构建和部署程序为**canister 智能合约**。本节提供有关canister生命周期以及如何管理canister的信息。

[[create-canister]]
== 获取 canister 标识符

根据您喜欢的开发工作流程，您可以在准备好编译程序之前或之后获取 canister 智能合约的唯一标识符。 例如，如果您想在编写任何代码之前为子网上的容器智能合约保留一个唯一标识符，您可以通过运行 dfx canister create 命令来实现。 此命令实质上创建了一个空的 canister 占位符，您可以稍后将代码安装到其中。 生成的 canister 将获得唯一标识符。

为 canister 注册唯一标识符：

. 在本地计算机打开终端
. 通过运行与以下命令类似的命令，为计划创建的Canister创建一个新项目。
+
[source,bash]
----
dfx new YOUR-PROJECT-NAME
----
+
请注意，默认情况下，您用于项目的名称也用作Canister名称。
. 进入新项目目录。
. 打开dfx.json配置文件，并设置要使用的Internet Computer网络的主机和端口。

如果您将本地主机用作Internet Computer网络提供者，则可以跳过此步骤。

如果您想在编译代码前为其他Canister创建标识符，在配置文件中可以随意修改Canister名字或添加Canister设置。

. 运行以下命令启动Internet Compter网络。
+
[source,bash]
----
dfx start --background
----
+
在大多数情况下，仅当您在本地运行Internet Computer网络时，才需要执行此步骤。‌
+
如果要注册要在远程网络上运行的Canister，则应包括--network命令行选项，以在该网络上执行任务。

. 通过运行以下命令，为dfx.json中定义的Canister注册唯一标识符。
+
[source,bash]
----
dfx canister create --all
----
+
该命令创建.dfx/local目录，并将canister_ids.json文件添加到该目录。

[[local-id]]
== Build a canister smart contract with a local identifier

After you have written source code for your project, you need to compile it into a WebAssembly module before deploying it as a canister.

If you are only compiling your project for local debugging, you can generate a locally-defined identifier for your project.

To generate a locally-defined identifier:

. Create a project with the configuration settings and program logic to suit your needs.
. Start the local canister execution environment, if necessary.
+
If you were compiling canisters to run on a remote execution environment, e.g. the {IC} blockchain, you would include the `+--network+` command-line option to perform tasks on the environment specified under this parameter.
. Generate hard-coded local identifiers for the canisters defined in the `+dfx.json+` by running the following command:
+
[source,bash]
----
dfx build --check
----
+
Note that you must register unique canister identifiers to replace your locally-defined identifier before you can deploy the project on the {IC} blockchain.

////
=== Register a unique network-wide identifier

In the most common development workflow, you are assigned network-wide canister identifiers as part of the build process rather than before you have code ready to compile. 

Because this scenario is the most common, it is also the simplest. 

To register canister identifiers as part of the build process:

. Start the {IC} network, if necessary.
+
In most cases, this step is only necessary if you are using the local host as the {IC} network provider and have stopped the network locally.
. Build the WebAssembly executable by running the following command:
+
[source,bash]
----
dfx build
----

== Generate interface bindings for a canister
////

[[deploy-canister]]
== 在Internet Computer网络上部署Canister

编译程序后，可以将编译后的代码安装在本地运行的Internet Computer网络上，也可以安装在远程网络上。

预先创建的Canister标识符或在构建过程中创建的Canister标识符决定了在部署过程中代码的安装位置。

首次在Internet Computer网络上进行部署：

. 打开一个终端并进入项目目录。

. 如有必要，启动Internet Computer网络。
+
多数情况下，仅当您在本机运行Internet Computer网络，才需要执行该步骤。
+
如果Canister安装在远程网络上，则应包括--network命令行选项，以在该网络上执行任务。
. 验证您具有要部署的所有Canister的标识符。
. 运行以下命令部署所有Canister。
+
[source,bash]
----
dfx canister install --all
----

[[lookup-id]]
== 查找Canister标识符

所有Canister都具有唯一的，特定网络的标识符。

您通常需要使用这些标识符与Canister进行交互。 例如，如果要访问应用程序的前端Canister或使用Candid Web接口与服务进行交互，则必须指定适当的Canister标识符。

由于标识符是特定于网络的，因此用于存储信息的文件位于不同的目录中。 例如，本地部署的Canister的标识符位于项目的.dfx/local/canister_ids.json文件中。

您可以通过运行dfx canister id命令来查找任何特定Canister的标识符。 例如，要查找部署在本地网络上的名为lookup的Canister标识符，可以运行以下命令：
....
dfx canister id lookup
....

要查找由IC别名指定的网络上部署的同一Canister的标识符，请运行以下命令：
....
dfx canister --network=ic id lookup
....

[[add-wallet]]
== 为现有的Canister添加钱包

当您本地开发创建新项目时会同时自动创建一个默认钱包，如果想为原来创建的Canister添加一个钱包，您可强制用dfx通过手动步骤来生成。

为现有Canister添加钱包：

. 打开一个终端并进入项目目录。
. 如有必要，运行以下命令来停止Internet Computer网络。
+
[source,bash]
----
dfx stop
----
. 删除.dfx目录。
. 使用以下命令启动Internet Computer网络。
+
[source,bash]
----
dfx start --clean
----

[[reinstall-canister]]
== 重新安装Canister

在开发周期中，您可能会安装，然后随着调试和改进的需要替换程序。

在这种情况下，您可能希望保留已注册的Canister标识符，但不保留任何Canister的代码或状态。例如，您的Canister可能只包含您不想保留的测试数据，或者您可能决定完全更改程序，但想在先前安装的Canister标识符下重新安装。

在Internet Computer网络上重新安装： 

. 打开一个终端并进入项目目录。
. 如有必要，启动Internet Computer网络。
+
多数情况下，仅当您在本机运行Internet Computer网络，才需要执行该步骤。

+
如果Canister重新安装在远程网络上，则应包括--network命令行选项，以在该网络上执行任务。
. 验证您具有要重新部署的所有Canister的标识符。
. 运行以下命令以重新部署所有Canister
+
[source,bash]
----
dfx canister install --all --mode reinstall
----

请注意，无论Canister是否具有与之关联的代码或状态，都可以使用重新安装模式来替换。

[[set-owner]]
== 为拥有一个Canister设置身份

在大多数情况下，第一次运行dfx canister create命令时会自动为您创建一个默认用户身份。此默认身份包括为您的本地用户帐户生成的公钥和私钥对。通常，此默认标识还是您创建的所有项目和您部署的所有Canister的默认所有者。但是您可以创建和使用您选择的用户来代换默认用户。

例如，以下场景说明了创建一个registered_owner身份，该身份随后用于注册，构建，部署和调用pubs项目。

为项目设置身份：

. 运行以下命令创建新项目
+
[source,bash]
----
dfx new pubs
----
. 运行以下命令进入项目目录：
+
[source,bash]
----
cd pubs
----
. 运行以下命令在后台启用Internet Computer网络：
+
[source,bash]
----
dfx start --background
----
. 运行以下命令创建一个新的身份:
+
[source,bash]
----
dfx identity new registered_owner
----
. 运行以下命令，将当前用户设置为registered_owner
+
[source,bash]
----
dfx identity use registered_owner
----
. 运行以下命令为项目注册，构建和部署Canister：
+
[source,bash]
----
dfx canister create --all
dfx build --all
dfx canister install --all
----
+
这些命令使用registered_owner身份运行，从而使该用户成为已部署Canister的所有者。
. 运行以下命令，通过调用greet函数以验证部署是否成功：
+
[source,bash]
---- 
dfx canister call pubs greet '("Sam")'
----

[[running-state]]
== 管理Canister运行状态

After you deploy a canister, it can begin receiving and processing requests from users and from other canisters.
Canisters that are available to send requests and receive replies are considered in be in a **Running** state.

Although canisters are normally placed in the Running state by default, there are cases where you might want to temporarily or permanently stop a canister.
For example, you might want to stop a canister before upgrading it. 
Stopping a canister helps to ensure proper handling of any messages that are in progress and need to either run to completion or be rolled back. 
You might also want to stop a canister to clear its message queue cleanly as a prerequisite to deleting the canister.

// tag::check-status[]
You can check the current status of all canisters or a specified canister by running the `+dfx canister status+` command.
For example, to see the status for all canisters running on the local canister execution environment, you would run the following command:

[source,bash]
----
dfx canister status --all
----

This command returns output similar to the following if canisters are currently running:

....
Canister status_check's status is Running.
Canister status_check_assets's status is Running.
....
// end::check-status[]   

// tag::stop-status[]
You can stop canisters that are currently running by running the `+dfx canister stop+` command.

[source,bash]
----
dfx canister stop --all
----

This command displays output similar to the following:

....
Stopping code for canister status_check, with canister_id 75hes-oqbaa-aaaaa-aaaaa-aaaaa-aaaaa-aaaaa-q
Stopping code for canister status_check_assets, with canister_id cxeji-wacaa-aaaaa-aaaaa-aaaaa-aaaaa-aaaaa-q
....

If you were to rerun the `+dfx canister status+` command, you might see a status of `+Stopped+` indicating that there were no pending messages that needed to processed or a status of `+Stopping+` indicating that there were messages in-flight that needed to be addressed.
// end::stop-status[]

// tag::restart-status[]
To restart a canister-for example, after a successful canister upgrade—you can run the `+dfx canister start+` command.
For example, to restart all of the canisters, you would run the following command:

[source,bash]
----
dfx canister start --all
----

This command displays output similar to the following:

....
Starting code for canister status_check, with canister_id 75hes-oqbaa-aaaaa-aaaaa-aaaaa-aaaaa-aaaaa-q
Starting code for canister status_check_assets, with canister_id cxeji-wacaa-aaaaa-aaaaa-aaaaa-aaaaa-aaaaa-q
....
// tag::restart-status[]

[[upgrade-canister]]
== Upgrade a canister smart contract

Unlike a canister reinstall that preserves the canister identifier but no state, a canister upgrade enables you to preserve the state of a deployed canister, and change the code.
 
For example, assume you have a dapp that manages professional profiles and social connections.
If you want to add a new feature to the dapp, you need to be able to update the canister code without losing any of the previously-stored data.
A canister upgrade enables you to update existing canister identifiers with program changes without losing the program state.

NOTE: To preserve state when you are upgrading a canister written in {proglang}, be sure to use the `+stable+` keyword to identify the variables you want to preserve. For more information about preserving variable state in {proglang}, see link:../language-guide/upgrades{outfilesuffix}[Stable variables and upgrade methods].
If you are upgrading a canister written in Rust, you should use `+pre_upgrade+` and `+post_upgrade+` functions as illustrated in the link:https://github.com/dfinity/cdk-rs/blob/master/examples/asset_storage/src/asset_storage_rs/lib.rs[Rust CDK asset storage] example to ensure data is properly preserved after a canister upgrade.

To upgrade a canister:

. Open a new terminal and navigate to your project directory.
. Start the local canister execution environment, if necessary.
+
In most cases, this step is only necessary if you are running the canisters locally.
+
If you were registering canisters to run on a remote execution environment, e.g. the {IC} blockchain, you would include the `+--network+` command-line option to perform tasks on the environment specified under this parameter.
. Verify you have canister identifiers for all of the canisters you want to upgrade.
+
Note that your program must identify the variables for which to maintain state by using the `+stable+` keyword in the variable declaration.
+
For more information about declaring stable variables, see the _{proglang} Programming Language Guide_.
. Upgrade all of the canisters by running the following command:
+
[source,bash]
----
dfx canister install --all --mode upgrade
----

[[delete-canister]]
== Delete a canister smart contract

If you want to permanently delete a specific canister or all canisters for a specific project on a given deployment (either local, or remote), you can do so by running the `+dfx canister delete+` command.

Deleting a canister removes the canister identifier, code, and state.
Before you can delete a canister, however, you must first stop the canister to clear any pending message requests or replies.

To delete all canisters for a project:

. Open a new terminal and navigate to your project directory.
. Start the local canister execution environment, if necessary.
+
In most cases, this step is only necessary if you are running the canisters locally.
+
If you were deleting canisters to run on a remote execution environment, e.g. the {IC} blockchain, you would include the `+--network+` command-line option to perform tasks on the environment specified under this parameter.
. Check the status of the project canisters running on the local canister execution environment by running the following command:
+
[source,bash]
----
dfx canister status --all
----
. Stop all of the project canisters by running the following command:
+
[source,bash]
----
dfx canister stop --all
----
. Delete all of the project canisters by running the following command:
+
[source,bash]
----
dfx canister delete --all
----

////
== Fork a canister
<TBD - not in this release>

== Set the controller for a canister
<TBD - not in this release>
////
