= Download center
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

目前你能从本地计算机的终端 shell 中直接下载 {sdk-long-name}。

// tag::install[] 
[[install-latest]]
== 从终端直接安装最新版本

从终端命令行下载和安装：

. 在本机上打开一个终端 
+
例如，在 macOS 上，打开“应用程序”文件夹，然后打开“实用程序”，然后双击“终端”。

. 运行以下命令下载和安装 SDK 包：
+
[source,bash]
----
sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
----

[[install-version]]
== 从终端安装指定版本

如果您要安装指定版本，例如测试一个以前的版本，您可以修改命令以包含指定的版本号。

从终端命令行下载和安装指定版本：

. 在本机上打开一个终端。
. 将需要安装的版本号设置到环境变量 `DFX_VERSION`，并放置在 `+curl+` 命令前 
+
例如，安装 0.8.2 版本，运行下列命令：
+
[source,bash]
----
DFX_VERSION=0.8.2 sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
----

NOTE: If you are using the DFX_VERSION environment variable to install a version of the {sdk-short-name} not yet publicly available, see this link:http-middleware{outfilesuffix}[article] for an overview of what's changed. 

// end::install[]   

== Next steps

For information about the next steps to take, see link:developers-guide/tutorials-intro{outfilesuffix}[Tutorials] in the link:developers-guide/sdk-guide{outfilesuffix}[_SDK Developer Tools_].

To learn more about writing programs for the {IC} before you start experimenting with code, see link:developers-guide/concepts/concepts-intro{outfilesuffix}[Concepts].

For information about writing programs for the {IC} using {proglang}, see the link:language-guide/motoko{outfilesuffix}[_Motoko Programming Language Guide_].

////
== Download a packaged release

[width="100%",cols=3*,"35%,30%,35%",options="header",]
|===
|Version |Tag |Documentation and supported platforms
|SDK 0.5.2 (February 2020) |sdk-0.5.2-RELEASE |Release notes / changelog
+
Supported platforms

|SDK 0.5.4 (March 2020) |sdk-0.5.4-RELEASE |Release notes / changelog
+ Supported platforms
|===

== Use a package manager

[source,bash]
----
npm install dfx
----

[source,bash]
----
brew install dfx
----
////