= 添加访问控制
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
//:!page-repl:
:proglang: Motoko
:LEE: local canister execution environment
:IC: Internet Computer blockchain
:company-id: DFINITY

应用程序通常需要基于角色权限来控制不同用户可以执行的操作。为说明如何创建和切换用户身份，本教程创建一个简单的程序，对不同角色用户显示不同的问候语。

此例子中，有三个命名角色-owner, admin 和 authorized。

. 具有admin角色的用户显示You have a role with administrative privileges
. 具有authorized角色的用户显示Would you like to play a game?
. 没有分配这些角色的用户显示Nice to meet you!

此外，只有安装Canister的用户才授予owner角色，只有owner和admin角色才能分配角色给其他用户。

在较高级别上，每个用户都有一个公用/专用密钥对。 用户访问的公用密钥与容器标识符结合在一起，形成一个安全主体，然后可以用作消息调用方来验证对在Internet Computer上运行的容器进行的功能调用。 

下图提供了有关用户身份如何认证消息调用者的简化视图。

image::principal-identities.svg[]

== 开始之前

在开始本教程之前，验证以下内容：

* 您已按照下载和安装中的说明下载并安装了DFINITY Canister SDK软件包。
* 您已运行了至少一个可以创建默认用户身份的命令。您的默认用户身份信息存储在$HOME/.config/dfx/identity/目录。
* 如果您使用Visual Studio Code作为你的IDE，并已按安装语言编辑插件所述安装好了Motoko语言插件。
* 您已停止本地计算机上所有的Internet Computer进程。

== 创建新项目

为测试访问控制和切换用户身份创建新项目：

. 打开终端。
. 切换到Internet Computer目录。
. 运行以下命令创建新项目
+
[source,bash]
----
dfx new access_hello
----
. 运行下列命令进入项目目录。
+
[source,bash]
----
cd access_hello
----

== 修改默认程序

对于本教程，您将使用具有分配和检索角色功能的程序替换模板源代码文件。

修改默认程序：

. 在文本编辑器中打开src/access_hello/main.mo文件，然后删除现有内容。
. 将以下示例代码复制并粘贴到文件中：
+
[source.copy,motoko,no-repl]
----
include::example$access-hello/main.mo[]
----
+
让我们看一下该程序的一些关键要素：
+
--
* You might notice that the `+greet+` function is a variation on the `+greet+` function you have seen in previous tutorials. 
+
您可能会注意到greet函数是您在先前教程中看到的greet函数的变体。但是，在此程序中，greet函数使用消息调用方来确定应用的权限，并基于与调用方相关联的权限来确定要显示的问候。
* 该程序定义了两种自定义类型-一种用于Role，一种用于Permissions。
* Assign_roles函数使消息调用者可以将角色分配给与身份关联的主体。
* 使用callerPrincipal函数，您可以返回与身份关联的主体。
* 使用my_role函数可以返回与身份关联的角色。
--
. 保存并关闭main.mo文件。

== 启动本地网络

开始构建项目前，需要连接到本地或远程 ICP 网络。

启动本地网络需要 dfx.json 文件，需要确认在项目根目录进行操作。在这篇教程中，建议开启 2 个终端，一个启动网络，另一个管理项目。

启动网络步骤：

. 打开新的终端。
. 进入项目根目录。
. 使用下面的命令启动 ICP 本地网络。
+
[source,bash]
----
dfx start --background
----
+
打开新的终端这时可能会显示警告信息，这取决于使用的平台的安全策略配置。这时请选择允许。启动本地网络后，终端会显示网络操信息。
. 切换到项目终端。

== 注册构建并部署应用

连接到本地开发环境的Internet Computer网络后，可以通过运行dfx deploy命令在一个步骤中注册，构建和部署应用程序。 您还可以使用单独的dfx canister create，dfx build和dfx canister install命令独立执行每个步骤。

本地部署：

. 检查是否在项目根目录。
. 通过运行以下命令来注册，构建和部署access_hello后端程序。
+
[source,bash]
----
dfx deploy access_hello
----
+
....
Creating a wallet canister on the local network.
The wallet canister on the "local" network for user "default" is "rwlgt-iiaaa-aaaaa-aaaaa-cai"
Deploying: access_hello
Creating canisters...
Creating canister "access_hello"...
"access_hello" canister created with canister id: "rrkah-fqaaa-aaaaa-aaaaq-cai"
Building canisters...
Installing canisters...
Installing code for canister access_hello, with canister_id rrkah-fqaaa-aaaaa-aaaaq-cai
Deployed canisters.
....

== 检查当前的认证内容

在创建任何其他身份之前，让我们查看与您的默认身份相关联的账户标识符以及该默认身份的cycles钱包。 

在Internet Computer上，账户是用户，Canister，节点或子网的内部代表。 账户的文本表示形式是使用账户数据类型显示的外部标识符。

要查看您当前的身份和账户:

. 通过运行以下命令来验证当前活动身份：
+
[source,bash]
----
dfx identity whoami
----
+
该命令显示的输出类似于以下内容：
+
....
default
....
. 通过运行以下命令，检查账户以获取默认用户身份：
+
[source,bash]
----
dfx identity get-principal
----
+
输出类似以下内容：
+
....
zen7w-sjxmx-jcslx-ey4hf-rfxdq-l4soz-7ie3o-hti3o-nyoma-nrkwa-cqe
....
. 通过运行以下命令来检查与默认用户关联的角色：
+
[source,bash]
----
dfx canister --wallet=$(dfx identity get-wallet) call access_hello my_role
----
+
输出类似以下内容：

+
....
(opt variant { owner })
....

== Create a new user identity

To begin testing the access controls in our dapp, let's create some new user identities and assign those users to different roles.

To create a new user identity:

. Check that you are still in your project directory, if needed.
. Create a new administrative user identity by running the following command:
+
[source,bash]
----
dfx identity new ic_admin
----
+
The command displays output similar to the following:
+
....
Creating identity: "ic_admin".
Created identity: "ic_admin".
....
. Call the `+my_role+` function to see that your new user identity has not been assigned to any role.
+
[source,bash]
----
dfx --identity ic_admin canister call access_hello my_role
----
+
The command displays output similar to the following:
+
....
Creating a wallet canister on the local network.
The wallet canister on the "local" network for user "ic_admin" is "ryjl3-tyaaa-aaaaa-aaaba-cai"
(null)
....
. Switch your currently-active identity context to use the new `+ic_admin+` user identity and display the principal associated with the `+ic_admin+` user by running the following command:
+
[source,bash]
----
dfx identity use ic_admin && dfx identity get-principal
----
+
The command displays output similar to the following:
+
....
Using identity: "ic_admin".
c5wa6-3irl7-tuxuo-4vtyw-xsnhw-rv2a6-vcmdz-bzkca-vejmd-327zo-wae
....
. Check the principal used to call the `+access_hello+` canister smart contract by running the following command:
+
[source,bash]
----
dfx canister call access_hello callerPrincipal
----
+
The command displays output similar to the following:
+
....
(principal "ryjl3-tyaaa-aaaaa-aaaba-cai")
....
+
By default, the cycles wallet identifier is the principal used to call the methods in the `+access_hello+` canister smart contract.
To illustrate access control, however, we want to use the principal associated with the user context, not the cycles wallet.
Before we get to that step, though, let's assign a role to the `+ic_admin+` user. To do that, we need to switch to the `+default+` user identity that has the `+owner+` role.

== Assign a role to an identity

To assign the admin role to the ic_admin identity:

. Switch your currently-active identity context to use the `+default+` user identity by running the following command:
+
[source,bash]
----
dfx identity use default
----
. Assign the `+ic_admin+` principal the `+admin+` role by running a command similar to the following using Candid syntax:
+
[source,bash]
----
dfx canister --wallet=$(dfx identity get-wallet) call access_hello assign_role '((principal "c5wa6-3irl7-tuxuo-4vtyw-xsnhw-rv2a6-vcmdz-bzkca-vejmd-327zo-wae"),opt variant{admin})'
----

NOTE: Be sure to replace the `+principal+` hash with the one returned by the `+dfx identity get-principal+` command for the `+ic_admin+` identity.

+
Optionally, you can rerun the command to call the `+my_role+` function to verify the role assignment.
+
[source,bash]
----
dfx --identity ic_admin canister call access_hello my_role
----
+
The command displays output similar to the following:
+
....
(opt variant { admin })
....
. Call the `+greet+` function using the `+ic_admin+` user identity that you just assigned the `+admin+` role by running the following command:
+
[source,bash]
----
dfx --identity ic_admin canister call access_hello greet "Internet Computer Admin"
----
+
The command displays output similar to the following:
+
....
(
  "Hello, Internet Computer Admin. You have a role with administrative privileges.",
)
....

== Add an authorized user identity

At this point, you have a `+default+` user identity with the `+owner+` role and an `+ic_admin+` user identity with the `+admin+` role. 
Let's add another user identity and assign it to the `+authorized+` role. 
For this example, however, we'll use an environment variable to store the user's principal.

To add a new authorized user identity:

. Check that you are still in your project directory, if needed.
. Create a new authorized user identity by running the following command:
+
[source,bash]
----
dfx identity new alice_auth
----
+
The command displays output similar to the following:
+
....
Creating identity: "alice_auth".
Created identity: "alice_auth".
....
. Switch your currently-active identity context to use the new `+alice_auth+` user identity by running the following command:
+
[source,bash]
----
dfx identity use alice_auth
----
. Store the principal for the `+alice_auth+` user in an environment variable by running the following command:
+
[source,bash]
----
ALICE_ID=$(dfx identity get-principal)
----
+
You can verify the principal stored by running the following command:
+
[source,bash]
----
echo $ALICE_ID
----
+
The command displays output similar to the following:
+
....
b5quc-npdph-l6qp4-kur4u-oxljq-7uddl-vfdo6-x2uo5-6y4a6-4pt6v-7qe
....
+
. Use the `+ic_admin+` identity to assign the `+authorized+` role to `+alice_auth+` by running the following command:
+
[source,bash]
----
dfx --identity ic_admin canister call access_hello assign_role "(principal \"$ALICE_ID\", opt variant{authorized})"
----
. Call the `+my_role+` function to verify the role assignment.
+
[source,bash]
----
dfx --identity alice_auth canister call access_hello my_role
----
The command displays output similar to the following:
+
....
(opt variant { authorized })
....
. Call the `+greet+` function using the `+alice_auth+` user identity that you just assigned the `+authorized+` role by running the following command:
+
[source,bash]
----
dfx canister call access_hello greet "Alice"
----
+
The command displays output similar to the following:
+
....
(
  "Welcome, Alice. You have an authorized account. Would you like to play a game?",
)
....

== Add an unauthorized user identity

You have now seen a simple example of creating users with specific roles and permissions.
The next step is to create a user identity that is not assigned to a role or given any special permissions.

To add an unauthorized user identity:

. Check that you are still in your project directory, if needed.
. Check your currently-active identity, if needed, by running the following command:
+
[source,bash]
----
dfx identity whoami
----
. Create a new user identity by running the following command:
+
[source,bash]
----
dfx identity new bob_standard
----
+
The command displays output similar to the following:
+
....
Creating identity: "bob_standard".
Created identity: "bob_standard".
....
. Store the principal for the `+bob_standard+` user in an environment variable by running the following command:
+
[source,bash]
----
BOB_ID=$(dfx --identity bob_standard identity get-principal)
----
. Attempt to use the `+bob_standard+` identity to assign a role.
+
[source,bash]
----
dfx --identity bob_standard canister call access_hello assign_role "(principal \"$BOB_ID\", opt variant{authorized})"
----
+
This command returns an `+unauthorized+` error.
. Attempt to use the `+default+` user identity to assign `+bob_standard+` the `+owner+` role by running the following command:
+
[source,bash]
----
dfx --identity default canister --wallet=$(dfx --identity default identity get-wallet) call access_hello assign_role "(principal \"$BOB_ID\", opt variant{owner})"
----
+
This command fails because users cannot be assigned the `+owner+` role.
. Call the `+greet+` function using the `+bob_standard+` user identity by running the following command:
+
[source,bash]
----
dfx --identity bob_standard canister --no-wallet call access_hello greet "Bob"
----
+
The command displays output similar to the following:
+
....
("Greetings, Bob. Nice to meet you!")
....

== Set the user identity for multiple commands

So far, you have seen how to create and switch between user identities for individual commands. 
You can also specify a user identity you want to use, then run multiple commands in the context of that user identity.

To run multiple commands under one user identity:

. Check that you are still in your project directory, if needed.
. List the user identities currently available by running the following command:
+
[source,bash]
----
dfx identity list
----
+
The command displays output similar to the following with an asterisk indicating the currently-active user identity.
+
....
alice_auth
bob_standard
default *
ic_admin
....
+
In this example, the `+default+` user identity is used unless you explicitly select a different identity.
. Select a new user identity from the list and make it the active user context by running a command similar to the following:
+
[source,bash]
----
dfx identity use ic_admin
----
+ The command displays output similar to the following:
+
....
Using identity: "ic_admin".
....
+
If you rerun the `+dfx identity list+` command, the `+ic_admin+` user identity displays an asterisk to indicate it is the currently active user context.
+
You can now run commands using the selected user identity without specifying `+--identity+` on the command-line. 

== Stop the {LEE}

After you finish experimenting with the dapp and using identities, you can stop the {LEE} so that it doesn’t continue running in the background.

To stop the {LEE}:

. In the terminal that displays network operations, press Control-C to interrupt the local network process.

. Stop the {LEE} by running the following command:
+
[source,bash]
----
dfx stop
----

== Want to learn more?

If you are looking for more information about identity and authentication, check out the following related resources:

* link:../cli-reference/dfx-identity{outfilesuffix}[dfx identity (command reference)]
* link:../working-with-canisters{outfilesuffix}#set-owner[Set an identity to own a canister smart contract (how-to)]
