= 使用actor查询
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY

在link:../../quickstart/quickstart-intro{outfilesuffix}[快速开始]章节中, 已经了解过一个使用了actor对象和异步消息的简单应用。

接下来的教程中，会写一个使用基于actor的消息的应用。本篇教程会讲解如何修改Hello，World！应用来定义一个actor并在本地网络部署测试。

== 开始之前

开始前，需要检查下面的问题：

* 已经按照 link:../../quickstart/local-quickstart{outfilesuffix}#download-and-install[下载与安装]章节的步骤下载并安装了DFINITY Canister SDK。
* 本地电脑上已经关闭了ICP网络进程。

本篇教程需要大概20分钟。

== 创建新项目

创建项目步骤：

[arabic]
. 打开终端
. 进入工作目录
. 运行下面的命令来创建项目
+
[source,bash]
----
dfx new actor_hello
----
. 进入项目目录
+
[source,bash]
----
cd actor_hello
----

== Modify the default configuration

在 link:explore-templates{outfilesuffix}[探索默认项目]章节中, ，已经介绍了创建新项目会添加一个dfx.json配置文件到项目目录。

在本章节中，需要修改一些默认配置。

dfx.json配置修改步骤：

. 在编辑器中，打开 dfx.json 配置文件。
. 查看actor_hello项目中的默认配置。
. 注意源码的名称和路径以及输出文件都使用actor_hello项目名称。

+
例如，默认的canister名称是actor_hello并且默认的主程序路径是 src/actor_hello/main.mo.
+
这些文件和目录可以重命名，但是要确保这些文件和目录的名称和dfx.json配置文件中的一
致。
如果使用默认的目录和文件名称，则无需修改。
. 删除所有的actor_hello_assets配置。
+
本章节的示例程序无需使用如何前端资源，因此可以删除这些配置。
+
以下是删除actor_hello_assets配置后的示例配置。
+
....
include::example$define-actor-dfx.json[]
....
. 保存并关闭配置文件继续。

== 修改默认程序

在link:explore-templates{outfilesuffix}[探索默认项目] 章节，已经介绍了创建新项目会创建一个默认的src目录，并包含一个main.mo程序模板文件。

在本章节中，可以修改模板代码创建一个简单的使用actor的"Hello, World!"程序

源码修改步骤：

. 进入项目目录：
+
[source,bash]
----
cd src/actor_hello
----
. 编辑器中打开main.mo文件

+
接下来会编写一个可以输出"Hello, World!"的示例程序。
+
为了编译后的程序在ICP上运行，您的程序必须包含一个具有公共函数的 actor 对象。  

. 复制粘贴以下示例代码到main.mo文件
+
[source.copy,motoko,no-repl]
----
include::example$actor_hello.mo[]
----
+
代码解析
+
--
* 程序导入Debug模块来提供print功能
* 程序使用public query func来定义一个查询方法，在这个方法中，actor_hello程序不会对canister状态进行修改或执行更新数据的操作。
--
+
要获取有关查询调用的信息，请查看 link:../concepts/canisters-code{outfilesuffix}#query-update[query calls] in link:../concepts/canisters-code{outfilesuffix}#canister-state[Canisters include both program and state].
. 保存并关闭main.mo文件。

== 使用本地识别码构建应用

如果你只需要对这个简单程序做本地测试，那么，就不需要再ICP网络为这个程序的编译输出保留一个单独的Canister识别码。

在本节中，可以无需连接ICP网络来编译程序。dfx build命令可以创建一个本地硬编码的canister识别码。

测试程序时，在无需本地启动或连接ICP网络的情况下，你都可以使用这个本地识别码。

构建程序执行文件步骤：

. 进入项目目录
. 使用本地识别码构建程序命令
+
[source,bash]
----
dfx build --check
----
+
--check 选项使您能够在本地构建项目以验证它是否编译并检查生成的文件。 
+
因为dfx build --check命令仅生成一个临时标识符，所以您应该看到类似于以下内容的输出：
+
....
Building canisters to check they build ok. Canister IDs might be hard coded.
Building canisters...
....
+
如果程序成功编译，可以在.dfx/local/canisters 和 .dfx/local/canisters/actor_hello/ 查看输出的文件。
+
比如，使用tree命令查看创建的文件
+
[source,bash]
----
tree .dfx/local/canisters
----
+
命令输出
....
.dfx/local/canisters
├── actor_hello
│   ├── actor_hello.d.ts
│   ├── actor_hello.did
│   ├── actor_hello.did.js
│   ├── actor_hello.js
│   └── actor_hello.wasm
└── idl

2 directories, 5 files
....

== 部署项目

dfx build --check 命令不会部署到任何ICP网络。

如果要部署本项目，需要做以下步骤：

* 连接ICP网络
* 注册网络Canister识别码
* 部署Canister

在部署项目前，必须连接到本地运行或远程的ICP网络。连接到ICP网络后，必须生成一个独一无二，网络绑定的Canister识别码来替换本地定义的识别码。

本地部署步骤：

. 打开命令行，进入项目目录
. 启动本地ICP网络
+
[source,bash]
----
dfx start --background
----
+
本教程中，使用--background 选项启动在后台启动ICP网络。使用这个选项后，你可以继续输入命令无需打开另一个命令行窗口。
. 使用下面的命令为项目在本地ICP网络生成一个新的Canister识别码
+
[source,bash]
----
dfx canister create actor_hello
----
+
输出下面的内容:
+
....
Creating a wallet canister on the local network.
The wallet canister on the "local" network for user "pubs-id" is "rwlgt-iiaaa-aaaaa-aaaaa-cai"
Creating canister "actor_hello"...
"actor_hello" canister created with canister id: "rrkah-fqaaa-aaaaa-aaaaq-cai"
....
+
dfx canister create 命令会存储网络绑定的canister识别码到.dfx/local目录下的canister_ids.json文件。
+
....
{
  "actor_hello": {
    "local": "rrkah-fqaaa-aaaaa-aaaaq-cai"
  }
}
....
. 运行下列命令：
+
[source,bash]
----
dfx build
----
+
....
Building canisters...
....
. 使用下面的命令在本地ICP网络部署actor_hello 项目。
+
[source,bash]
----
dfx canister install actor_hello
----
+
命令输出:
+
....
Installing code for canister actor_hello, with canister_id rrkah-fqaaa-aaaaa-aaaaq-cai
....

== 查询Canister

现在，项目已经部署到本地ICP网络，并且可以使用dfx canister call命令进行测试。

测试部署的程序步骤如下：

. 使用dfx canister call命令调用hello函数:
+
[source,bash]
----
dfx canister call actor_hello hello
----
. 验证hello函数在本地网络进程中输出了相应的检查消息。
+
例如，程序会输出类似以下内容
+
....
[Canister rrkah-fqaaa-aaaaa-aaaaq-cai] Hello, World from DFINITY 
....
+
注意"Hello, World from DFINITY" 只会出现在显示本地ICP网络活动的命令行中。

== 关闭本地网络

完成程序的测试后，可以关闭ICP网络。

关闭步骤：

. 打开显示网络活动的命令行，摁下Control-C命令终止本地网络进程。
. 或通过命令行或操作系统来终止replica进程
. 运行下面的命令终止网络。
+
[source,bash]
----
dfx stop
----
