= 使用actor查询
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY

在link:../../quickstart/quickstart-intro{outfilesuffix}[快速开始]章节中, 已经了解过一个使用了actor对象和异步消息的简单应用。

接下来的教程中，会写一个使用基于actor的消息的应用。本篇教程会讲解如何修改Hello，World！应用来定义一个actor并在本地网络部署测试。

== 开始之前

开始前，需要检查下面的问题：

* 已经按照 link:../../quickstart/local-quickstart{outfilesuffix}#download-and-install[下载与安装]章节的步骤下载并安装了DFINITY Canister SDK。
* 本地电脑上已经关闭了ICP网络进程。

本篇教程需要大概20分钟。

== 创建新项目

创建项目步骤：

[arabic]
. 打开终端
. 进入工作目录
. 运行下面的命令来创建项目
+
[source,bash]
----
dfx new actor_hello
----
. 进入项目目录
+
[source,bash]
----
cd actor_hello
----

== Modify the default configuration

在 link:explore-templates{outfilesuffix}[探索默认项目]章节中, ，已经介绍了创建新项目会添加一个dfx.json配置文件到项目目录。

在本章节中，需要修改一些默认配置。

dfx.json配置修改步骤：

. 在编辑器中，打开 dfx.json 配置文件。
. 查看actor_hello项目中的默认配置。
. 注意源码的名称和路径以及输出文件都使用actor_hello项目名称。

+
例如，默认的canister名称是actor_hello并且默认的主程序路径是 src/actor_hello/main.mo.
+
这些文件和目录可以重命名，但是要确保这些文件和目录的名称和dfx.json配置文件中的一
致。
如果使用默认的目录和文件名称，则无需修改。
. 删除所有的actor_hello_assets配置。
+
本章节的示例程序无需使用如何前端资源，因此可以删除这些配置。
+
以下是删除actor_hello_assets配置后的示例配置。
+
....
include::example$define-actor-dfx.json[]
....
. 保存并关闭配置文件继续。

== 修改默认程序

在link:explore-templates{outfilesuffix}[探索默认项目] 章节，已经介绍了创建新项目会创建一个默认的src目录，并包含一个main.mo程序模板文件。

在本章节中，可以修改模板代码创建一个简单的使用actor的"Hello, World!"程序

源码修改步骤：

. 进入项目目录：
+
[source,bash]
----
cd src/actor_hello
----
. 编辑器中打开main.mo文件

+
接下来会编写一个可以输出"Hello, World!"的示例程序。
+
为了编译后的程序在ICP上运行，您的程序必须包含一个具有公共函数的 actor 对象。  

. 复制粘贴以下示例代码到main.mo文件
+
[source.copy,motoko,no-repl]
----
include::example$actor_hello.mo[]
----
+
代码解析
+
--
* 程序导入Debug模块来提供print功能
* 程序使用public query func来定义一个查询方法，在这个方法中，actor_hello程序不会对canister状态进行修改或执行更新数据的操作。
--
+
要获取有关查询调用的信息，请查看 link:../concepts/canisters-code{outfilesuffix}#query-update[query calls] in link:../concepts/canisters-code{outfilesuffix}#canister-state[Canisters include both program and state].
. 保存并关闭main.mo文件。

== Checking that the canister builds

Usually, in order to build a canister, it's necessary to first reserve a unique canister identifier
on the {IC} blockchain mainnet.

However, it's also possible to compile your program without connecting to the {IC} blockchain mainnet at all.
The `+dfx build --check+` command uses a temporary, hard-coded canister identifier to accomplish this.

To check that the canister builds:

. Navigate back to the root of your project directory.
. Build the canister executable with a temporary, hard-coded identifier by running the following command:
+
[source,bash]
----
dfx build --check
----
+
The `+--check+` option enables you to build a project locally to verify that it compiles and to inspect the files produced.
Because the `+dfx build --check+` command only uses a temporary identifier, you should see output similar to the following:
+
....
Building canisters to check they build ok. Canister IDs might be hard coded.
Building canisters...
....
+
If the canister compiles successfully, you can inspect the output in the default `+.dfx/local/canisters+` directory and `+.dfx/local/canisters/actor_hello/+` subdirectory.
+
For example, you might use the `+tree+` command to review the files created:
+
[source,bash]
----
tree .dfx/local/canisters
----
+
The command displays output similar to the following
....
.dfx/local/canisters
├── actor_hello
│   ├── actor_hello.d.ts
│   ├── actor_hello.did
│   ├── actor_hello.did.js
│   ├── actor_hello.js
│   └── actor_hello.wasm
└── idl

2 directories, 5 files
....

== Deploy the project

You cannot deploy the output from the `+dfx build --check+` command to  a local canister execution environment or the {IC} mainnet.
If you wanted to deploy this project, you would need to do the following:

* Connect to the either the local canister execution environment or {IC} mainnet.
* Register a connection-specific canister identifier.
* Deploy the canister.

Let's consider these steps in a bit more detail.
Before you can deploy this project, you must connect to either your local canister execution environment, provided by `dfx`, or to the Internet Computer blockchain mainnet.
After you connect to a local canister execution environment or {IC} mainnet, you must also generate a unique, *connection-specific* canister identifier to replace your locally-defined identifier.
To see the steps involved for yourself, let's deploy the project locally.

To deploy this project locally:

. Open a terminal and navigate to your project directory, if needed.
. Start the local canister execution environment on your local computer by running the following command:
+
[source,bash]
----
dfx start --background
----
+
For this tutorial, you can use the `+--background+` option to start the local canister execution environment as background processes.
With this option, you can continue to the next step without opening another terminal shell on your local computer.
. Generate a new canister identifier for your project on the local canister execution environment by running the following command:
+
[source,bash]
----
dfx canister create actor_hello
----
+
You should see output similar to the following:
+
....
Creating a wallet canister on the local network.
The wallet canister on the "local" network for user "pubs-id" is "rwlgt-iiaaa-aaaaa-aaaaa-cai"
Creating canister "actor_hello"...
"actor_hello" canister created with canister id: "rrkah-fqaaa-aaaaa-aaaaq-cai"
....
+
The `+dfx canister create+` command also stores the connection-specific canister identifier in a `+canister_ids.json+` file in the `+.dfx/local+` directory.
+
For example:
+
....
{
  "actor_hello": {
    "local": "rrkah-fqaaa-aaaaa-aaaaq-cai"
  }
}
....
. Build the canister by running the following command:
+
[source,bash]
----
dfx build
----
The command displays output similar to the following:
+
....
Building canisters...
....
. Deploy your `+actor_hello+` project on the local canister execution environment by running the following command:
+
[source,bash]
----
dfx canister install actor_hello
----
+
The command displays output similar to the following:
+
....
Installing code for canister actor_hello, with canister_id rrkah-fqaaa-aaaaa-aaaaq-cai
....

== Query the canister

You now have a canister deployed on your local canister execution environment and can test your canister by using the `+dfx canister call+` command.

To test the canister you have deployed on the local canister execution environment:

. Use `+dfx canister call+` to call the `+hello+` function by running the following command:
+
[source,bash]
----
dfx canister call actor_hello hello
----
. Verify that the command returns the text specified for the `+hello+` function along with a checkpoint message in the terminal running the local canister execution environment.
+
For example, the canister displays "Hello, World from DFINITY" in output similar to the following:
+
....
[Canister rrkah-fqaaa-aaaaa-aaaaq-cai] Hello, World from DFINITY 
....
+
Note that if you are running the Internet Computer mainnet in a separate terminal instead of in the background, the "Hello, World from DFINITY" message is displayed in the terminal that displays mainnet activity.

== Stop the local canister execution environment

After you finish experimenting with your canister, you can stop the local canister execution environment so that it doesn’t continue running in the background.

To stop the local canister execution environment, you can:

. In the terminal used to interact with your canister, issue the command `dfx stop`; or
. In the terminal that displays operations from the local canister execution environment, press Control-C to interrupt that process; or
. Kill the `replica` process using commands or tools of your operating system.

. Stop the local canister execution environment by running the following command:
+
[source,bash]
----
dfx stop
----
