= 使用多个actor
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY

在本章节中，将会创建一个由多个actor的项目。到目前为止，我们只在一个Motoko文件中定义一个actor，并且一个actor会编译到一个canister。我们也可以创建一个由多个actor的项目并且从一个dfx.json构建多个canister。

在本章节中，你将在同一个项目中创建单独的程序文件，并包含3个actor。这个项目定义了以下不相关的actor

* assistant actor提供to-do list的添加和查看任务的函数
+
为了简单，本教程的示例代码只包含添加to-do list任务和查看已添加任务的功能。本程序更完整的版本-有更多功能比如标记任务完成和从to-do list删除任务-可以在link:https://github.com/dfinity/examples/[examples] 代码库的 link:https://github.com/dfinity/examples/tree/master/motoko/simple-to-do[Simple to-do checklist]查看。

* rock_paper_scissors actor 提供硬编码的"石头剪刀布"比赛中决定赢家的函数。
+
这个示例代码描述了在Motoko中switch和case的用法

* daemon actor提供了启动和结束守护进程的模拟函数。
+
这个示例代码会简单地赋值一个变量并打印演示信息。

== 开始之前

开始前，需要检查下面的问题

* 已经按照link:../../quickstart/local-quickstart{outfilesuffix}#download-and-install[下载与安装]章节的步骤下载并安装了DFINITY Canister SDK
* 本地电脑上已经关闭了ICP网络进程
本篇教程需要大概20分钟。

== 创建新项目

创建项目步骤：

[arabic]
. 打开终端
. 进入工作目录
. 行下面的命令来创建项目
+
[source,bash]
----
dfx new multiple_actors
----
. 进入项目目录
+
[source,bash]
----
cd multiple_actors
----

== 修改默认配置

在探索默认项目章节，已经介绍了创建新项目会添加一个dfx.json配置文件到项目目录。在本章节中，需要修改一些默认配置指定定义actor的程序位置。

dfx.json配置修改步骤

. 在编辑器中，打开 dfx.json 配置文件，然后修改默认的multiple_actors canister名称和源码目录为assistant。
+
例如，在canisters键：
+
[source,json]
----
    "assistant": {
      "main": "src/assistant/main.mo",
      "type": "motoko"
    },
----
+
由于你已经在配置文件中添加了这个canisters的设置，你必须要在大括号后面添加一个逗号来包裹assistant的配置。

. 删除文件中的multiple_actors_assets部分
. 为rock_paper_scissors和daemon程序添加新的canister名称，源码位置和类型
+
修改后的配置文件如下
+
[source,json]
----
include::example$multiple-actors/dfx.json[]
----
+

. 保存并关闭配置文件继续
. 运行下面的命令修改默认源码文件名称匹配dfx.json文件中的配置
+
[source,bash]
----
cp -r src/multiple_actors/ src/assistant/
----
. 运行下面的命令复制assistant源码文件目录为rock_paper_scissors acotr创建主程序文件
+
[source,bash]
----
cp -r src/assistant/ src/rock_paper_scissors/
----
. 运行下面的命令复制assistant源码文件目录为daemon创建主程序文件
+
[source,bash]
----
cp -r src/assistant/ src/daemon/
----

== 修改默认程序

现在src目录有三个独立的目录，每个都包含main.mo模板文件。本章节中，你需要用不同的actor替换每个main.mo文件。‌

修改源码步骤如下:

. 打开src/assistant/main.mo文件并删除已有内容
. 复制粘贴下面的代码

+
[source.copy,motoko,no-repl]
----
include::example$multiple-actors/assistant/main.mo[]
----

. 保存并关闭main.mo文件
. 打开src/rock_paper_scissors/main.mo文件并删除已有内容
. 复制粘贴下面的代码

+
[source.copy,motoko,no-repl]
----
include::example$multiple-actors/rock_paper_scissors/main.mo[]
----

. 保存并关闭main.mo文件
. 打开src/daemon/main.mo文件并删除已有内容
. 复制粘贴下面的代码

+
[source.copy,motoko,no-repl]
----
include::example$multiple-actors/daemon/main.mo[]
----

. 保存并关闭main.mo文件

== 保存并关闭main.mo文件

开始构建项目前，需要连接到本地或远程 ICP 网络。

启动本地网络需要 dfx.json 文件，需要确认在项目根目录操作。在这篇教程中，建议开启 2 个终端，一个启动网络，另一个管理项目。

启动网络步骤:

[arabic]
. 打开新的终端
. 进入项目根目录
. 使用下面的命令启动 ICP 本地网络 
+
[source,bash]
----
dfx start
----
. 切换到项目终端

== 注册构建并部署应用

在开发环境中连接到本地ICP网络后，就可以在本地注册构建部署应用了。

部署本地应用步骤:

. 检查是否在项目根目录
. 注册构建并部署应用命令

+
[source,bash]
----
dfx deploy
----

如果你可以访问远程ICP网络，你可以使用--netowrk选项和dfx.json文件中定义的网络配置指定要部署的网络。

例如，如果你连接到了ic指定的网络，可以运行下面的命令：

[source,bash]
----
dfx deploy --network ic
----
dfx deploy命令会输出执行的操作信息，例如
....
Deploying all canisters.
Creating canisters...
Creating canister "assistant"...
"assistant" canister created with canister id: "75hes-oqbaa-aaaaa-aaaaa-aaaaa-aaaaa-aaaaa-q"
Creating canister "daemon"...
"daemon" canister created with canister id: "cxeji-wacaa-aaaaa-aaaaa-aaaaa-aaaaa-aaaaa-q"
Creating canister "rock_paper_scissors"...
"rock_paper_scissors" canister created with canister id: "7kncf-oidaa-aaaaa-aaaaa-aaaaa-aaaaa-aaaaa-q"
....

== 调用函数验证部署

现在你已经在本地网络部署了三个canister并且可以通过dfx canister call命令分别测试

测试步骤:

. 使用dfx canister call命令调用assistant canister，使用addTodo函数并传递要添加的任务
+
[source,bash]
----
dfx canister call assistant addTodo '("Schedule monthly demos")'
----
. 使用showTodos函数验证命令返回的to-do list
+
[source,bash]
----
dfx canister call assistant showTodos
----
+
命令输出
+
....
("___TO-DOs___(1) Schedule monthly demos")
....
. 使用dfx canister call命令调用rock_paper_scissors canister，使用contest函数
+
[source,bash]
----
dfx canister call rock_paper_scissors contest
----
+
命令输出
+
....
("Bob won")
....
. 使用dfx canister call命令调用daemon canister，使用launch函数
+
[source,bash]
----
dfx canister call daemon launch
----
. 验证launch模拟函数返回“The daemon process is running”信息
+
....
(""The daemon process is running"")
....

== 关闭本地网络

完成程序的测试后，可以关闭ICP网络

关闭步骤：

. 打开显示网络活动的命令行，摁下Control-C命令终止本地网络进程
. 运行下面的命令终止网络
+
[source,bash]
----
dfx stop
----

////
== Import an actor

To extend what you have learned in this tutorial, you might want to try modifying the source code to return different results.
 
As features are added, the tutorial can be modified to illustrate other functionality such as:
- How to import an actor
- How to call a function in another actor
- How to include multiple actors in a single program
- How and when to add an actor class

////
