= 从钱包接受cycles
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
//:!page-repl:
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY

在进行本地开发时，可以使用项目中的默认钱包发送Cycles并检查余额。 但是关于需要接收和燃烧这些Cycles以执行功能并向用户提供服务是如何工作的呢？ 

本教程提供了一个简单的示例，以说明如何添加功能以接收Cycles并检查余额。

此示例包括以下内容：

* wallet_balance函数使您可以检查Canister的当前Cycles余额。
* wallet_receive函数使程序能够接受发送到Canister的Cycles。
* greet函数接受文本参数，并在终端中显示问候语。
* owner函数返回消息调用者使用的账户。

== 开始之前

在开始本教程之前，请确保具备以下开发条件

* 您已下载并安装 DFINITY Canister SDK 扩展包， link:../../quickstart/local-quickstart{outfilesuffix}#download-and-install[安装说明]。
* 如果您使用 Visual Studio Code 开发，请确保安装了 Motoko 语言的相关插件，link:../../quickstart/local-quickstart{outfilesuffix}#install-vscode[安装说明]。
* 确保本地开发环境中，已关停全部的网络进程。


== 创建新项目

执行以下操作创建新的项目目录：

[arabic]
. 打开终端。
. 进入工作目录。
. 通过运行以下命令来创建一个新项目
+
[source,bash]
----
dfx new cycles_hello
----
. 进入项目目录。
+
[source,bash]
----
cd cycles_hello
----

== 修改默认程序

在本教程中，您将修改模板源代码，以包含用于接受Cycles和检查余额的新功能。

. 在文本编辑器中打开src/cycles_hello/main.mo文件，然后删除现有内容。
. 将以下示例代码复制并粘贴到文件中。
+
[source.copy,motoko,no-repl]
----
include::example$cycles-main.mo[]
----
+
让我们看一下该程序的一些关键要素：
+
--
* 该程序导入Motoko基础库ExperimentalCycles，该库提供处理Cycles的基本功能。
* 该程序使用一个actor类，而不是单个actor，以便它可以具有多个actor实例，以接受不同的Cycles数量，直至所有实例的容量。
* 容量作为参数传递给actor类。
* msg.caller标识与该调用关联的账户。
--
. 保存并关闭文件。

== 启动本地网络 

开始构建项目前，需要连接到本地或远程 ICP 网络。

启动本地网络需要 dfx.json 文件，需要确认在项目根目录进行操作。在这篇教程中，建议开启 2 个终端，一个启动网络，另一个管理项目。

启动网络步骤：

[arabic]
. 打开新的终端。
. 进入项目根目录。
. 使用下面的命令启动 ICP 本地网络。
+
[source,bash]
----
dfx start --clean --background
----



== 注册构建并部署应用

连接到本地开发环境的Internet Computer网络后，可以在本地注册，构建和部署应用程序。

. 进入项目根目录。
. 通过运行以下命令来注册，构建和部署您的应用程序。
+
[source,bash]
----
dfx deploy --argument '(360000000000)'
----
+
本示例将Canister的容量设置为360,000,000,000个Cycles。 dfx deploy命令输出显示有关其执行的操作的信息，包括与为此本地项目创建的钱包Canister关联的标识以及钱包Canister标识符。
+
例如：
+
....
Deploying all canisters.
Creating canisters...
Creating canister "cycles_hello"...
Creating the canister using the wallet canister...
Creating a wallet canister on the local network.
The wallet canister on the "local" network for user "default" is "rwlgt-iiaaa-aaaaa-aaaaa-cai"
"cycles_hello" canister created with canister id: "rrkah-fqaaa-aaaaa-aaaaq-cai"
Creating canister "cycles_hello_assets"...
Creating the canister using the wallet canister...
"cycles_hello_assets" canister created with canister id: "ryjl3-tyaaa-aaaaa-aaaba-cai"
Building canisters...
Building frontend...
Installing canisters...
Installing code for canister cycles_hello, with canister_id rrkah-fqaaa-aaaaa-aaaaq-cai
Installing code for canister cycles_hello_assets, with canister_id ryjl3-tyaaa-aaaaa-aaaba-cai
Authorizing our identity (default) to the asset canister...
Uploading assets to asset canister...
Deployed canisters.
....

== 测试应用

在本地Internet Computer网络上部署该应用程序之后，您可以使用dfx canister call命令尝试钱包功能并测试程序。

. 通过运行以下命令，检查账户以获取默认用户身份。
+
[source,bash]
----
dfx canister call cycles_hello owner
----
+
该命令针对当前身份显示类似于以下内容的输出：
+
....
(principal "g3jww-sbmtm-gxsag-4mecu-72yc4-kef5v-euixq-og2kd-sav2v-p2sb3-pae")
....
+
如果您尚未更改用于运行dfx deploy命令的身份，则应通过运行dfx identity get-principal命令获得相同的账户。
这很重要，因为您必须是钱包Canister的所有者才能执行某些任务，例如Cycles周期或授予其他保管者身份发送Cycles的权限。
. 通过运行以下命令检查初始钱包Cycles余额。
+
[source,bash]
----
dfx canister call cycles_hello wallet_balance
----
+
您尚未向Canister发送任何Cycles，因此该命令显示以下余额：
+
....
(0)
....
. 通过运行类似以下命令，从默认的钱包Canister发送到cycles_hello。
+
[source,bash]
----
dfx canister call rwlgt-iiaaa-aaaaa-aaaaa-cai wallet_send '(record { canister = principal "rrkah-fqaaa-aaaaa-aaaaq-cai"; amount = (256000000000:nat64); } )'
----
. 调用wallet_balance函数，以查看cycles_hello Canister具有的Cycles数量。

+
[source,bash]
----
dfx canister call cycles_hello wallet_balance
----
+
该命令显示的输出类似以下内容：
+
....
(256_000_000_000)
....
. 通过运行类似于以下命令，调用wallet_balance函数以查看默认钱包中的Cycles数。
+
[source,bash]
----
dfx canister call rwlgt-iiaaa-aaaaa-aaaaa-cai wallet_balance
----
+
该命令使用Candid格式返回钱包Canister的余额记录。 
+
例如，该命令可能显示一条记录，其中包含金额字段（由哈希3_573_748_184表示），余额为97,738,624,621,042个Cycles，如下所示：
+
....
(record { 3_573_748_184 = 97_738_624_621_042 })
....
+
对于这个简单的教程，Cycles仅从默认钱包Canister中的余额中消耗，而不是从cycles_hello Canister中消耗。
. 通过运行类似于以下命令的命令来调用greet函数。
+
[source,bash]
----
dfx canister call cycles_hello greet '("from DFINITY")'
----
. 重新调用wallet_balance函数，以查看从默认钱包中扣除的Cycles数。
+
[source,bash]
----
dfx canister call rwlgt-iiaaa-aaaaa-aaaaa-cai wallet_balance
----
+
例如，您可能会得到类似以下的结果：
+
....
(record { 3_573_748_184 = 97_638_622_179_500 })
....

== 关闭本地网络

完成程序的测试后，可以关闭ICP网络。

关闭步骤

. 打开显示网络活动的命令行，摁下Control-C命令终止本地网络进程。
. 运行下面的命令终止网络。
+
[source,bash]
----
dfx stop
----

== 更多内容

如果您正在寻找有关使用Cycles的更多信息，请查看以下相关资源

* link:../concepts/tokens-cycles{outfilesuffix}[代币和Cycles（概述）]
* link:../cli-reference/dfx-identity{outfilesuffix}[dfx身份（命令参考）]
* link:../working-with-canisters{outfilesuffix}#set-owner[设置身份以拥有一个Canister（手把手）]
* link:../../language-guide/cycles{outfilesuffix}[管理Cycles（语言参考）]
* link:../../base-libraries/ExperimentalCycles{outfilesuffix}[试验Cycles（基本模块）]
